apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: financial-analytics-platform
type: Opaque
data:
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW5wYXNz   # base64-encoded "adminpass" (replace with your password)
