{{- range .Values.microservices }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-secret
  namespace: financial-analytics-platform
type: Opaque
data:
  vault-token: {{ $.Values.vault.token | b64enc }}
{{- end }}
