apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: financial-analytics-platform
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "500Mi"
            cpu: "250m"
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: discovery.type
          value: "single-node"           # Run Elasticsearch in single-node mode
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"     # Set JVM heap size
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: es-data
        emptyDir: {}                     # Ephemeral storage, replace with PersistentVolume if needed
