apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: financial-analytics-platform
spec:
  ports:
  - port: 9200
    targetPort: 9200
    name: http
  - port: 9300
    targetPort: 9300
    name: transport
  selector:
    app: elasticsearch
