apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: financial-analytics-platform
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    filter {
      # Example filter to add fields or modify log structure
      grok {
        match => { "message" => "%{COMMONAPACHELOG}" }
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch.financial-analytics-platform.svc.cluster.local:9200"]
        index => "logstash-%{+YYYY.MM.dd}"
      }
      stdout { codec => rubydebug }
    }
