apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: financial-analytics-platform
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.10.2
        ports:
        - containerPort: 5044     # Beats input port
        - containerPort: 9600     # HTTP API port
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          subPath: logstash.conf
      volumes:
      - name: config-volume
        configMap:
          name: logstash-config
