apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: financial-analytics-platform
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.10.2
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "500Mi"
            cpu: "250m"
        ports:
        - containerPort: 5601  # Kibana's default port
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch.financial-analytics-platform.svc.cluster.local:9200"
        - name: SERVER_HOST
          value: "0.0.0.0"  # Bind to all network interfaces
